
language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - which phpunit
  - phpunit

script: phpunit tests/TestCase.php

matrix:
  fast_finish: true